name: CI/CD
# 触发条件为 push
on:
  push:
    branches:
      - main
    # 修改文件范围, 不在范围内不触发
    paths:
      - '.github/workflows/**'
      - '__test__/**'
      - 'src/**'
      - 'vite.config.js'
# 任务
jobs:
  test:
    # 运行的环境
    runs-on: ubuntu-latest
    # 步骤
    steps:
      - uses: actions/checkout@v2 # git pull
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: node -v
            - run: npm install
            - run: npm run build
            - name: Deploy # 部署
              uses: JamesIves/github-pages-deploy-action@v4.3.3
              with:
                  branch: gh-pages # 部署后提交到那个分支
                  folder: dist # 这里填打包好的目录名称


